### ISSUE TITLE
阿里云的sls上没有content字段

### ISSUE THREAD

**Issue by edwardhey** [aliyun/aliyun-log-jaeger#2]
请问是否没有同步span.Logs的内容到sls？因为在使用jaeger的时候查看spin没有Logs那一项

谢谢

**Comment by bcho** [comment]
我也遇到类似的问题，请问 @edwardhey 你有解决吗？ cc @brucewu-fly

**Comment by edwardhey** [comment]
要稍微改下阿里的这个插件，把log当作json发过去给sls，就可以了 @bcho

**Comment by brucewu-fly** [comment]
@bcho 您好，此版本的 jaeger 并未带上 Logs 参数，因为当初开发的时候服务端还不支持 json。后续我们会把 logs 字段带上

**Comment by bcho** [comment]
@brucewu-fly 新版本近期会发布吗？

**Comment by brucewu-fly** [comment]
@edwardhey @bcho 您好，我们已发布相应版本，欢迎试用。 https://github.com/aliyun/aliyun-log-jaeger/releases
