### ISSUE TITLE
jaegertracing/jaeger-agent镜像版本导致命令失效

### ISSUE THREAD

**Issue by yuyiyu2017** [aliyun/aliyun-log-jaeger#5]
docker安装jaeger-agent时，必须指定版本为 1.6 以前的，因为后续版本中 "/go/bin/agent-linux" 默认执行。
  如果不加版本，将使用 lastest 版本，将会报错 “no command /go/bin/agent-linux”。
  文件 aliyunlog-jaeger-docker-compose.yml 中也会出现同样的问题。
  
![default](https://user-images.githubusercontent.com/33891555/45141755-5963a900-b1e9-11e8-8ab5-007d18fcd6a4.png)

**Comment by brucewu-fly** [comment]
好的，感谢提醒。我们修改下 docker-compose
