### ISSUE TITLE
How to support service dependencies

### ISSUE THREAD

**Issue by osswangxining** [aliyun/aliyun-log-jaeger#6]
Jaeger support the capabilities to collect spans from storage, analyze links between services, and store them for later presentation in the UI. 
https://github.com/jaegertracing/spark-dependencies

In this Jaeger on Aliyun Log Service , how to provide this feature too? I cannot find how to configure this.

**Comment by brucewu-fly** [comment]
Jaeger on Aliyun Log Service doesn't support calculate dependencies now.
We plan to support it after the ETL framework ready which is similar with spark-dependencies.

**Comment by perfectnewer** [comment]
Can I known your time plan?
